name: pull requests

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-title-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Enforce PR title format
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: feat, fix, chore, refactor, test, docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Update dependencies
        run: composer update --no-interaction --prefer-dist --no-progress

      - name: Run tests
        run: ./vendor/bin/pest

  label-and-comment:
    runs-on: ubuntu-latest
    needs: validate-title-and-run-tests

    steps:
      - name: Add 'needs review' label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          labels: |
            needs review

      - name: Comment on the PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thanks for your pull request! A reviewer will take a look shortly. 🚀"
            })

      - name: Check if PR is from a fork
        id: fork_check
        run: |
          echo "is_fork=$([[ '${{ github.event.pull_request.head.repo.full_name }}' != '${{ github.repository }}' ]] && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Greet external contributor
        if: steps.fork_check.outputs.is_fork == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Welcome contributor from a forked repository! 🎉 We appreciate your input."
            })
